In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("tech_layoffs2.csv")

In [4]:
df

,company,total_layoffs,impacted_workforce_percentage,reported_date,industry,headquarter_location,sources,status,additional_notes
0,C2FO,20,2,2022-12-09,"Fintech, payments","Leawood, KS",Kansas City Business Journal,Private,NaN
1,VideoAmp,Unclear,2,2022-09-19,Advertising platforms,Los Angeles,Company memo,Private,NaN
2,Amperity,13,3,2022-08-20,"Saas, analytics",Seattle,Geekwire,Private,NaN
3,Addepar,20,3,2023-01-18,"fintech, data analytics","Mountain View, CA",Fortune,Private,NaN
4,Thirty Madison,24,3,2022-05-13,Health Care,New York,Axios,Private,"Per Axios, 22 of the employees laid off were f..."
...,...,...,...,...,...,...,...,...,...
484,Salesforce,9090,Unclear,2023-01-04,"enterprise tech, analytics",San Francisco,New York Times,Public,NaN
485,Oracle,Unclear,Unclear,2022-08-01,"SaaS, enterprise software",Austin,The Information,Public,The Information reported thousands of people w...
486,LivePerson,Unclear,Unclear,2022-09-15,Customer service,New York,LinkedIn,Public,NaN
487,Skillz,Unclear,Unclear,2022-08-29,"Mobile Apps, Gaming",San Francisco,Seeking Alpha,Public,NaN
488,Blueboard,Unclear,Unclear,2022-11-03,Enterprise Software,San Francisco,LinkedIn reports,Private,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company                        489 non-null    str
 1   total_layoffs                  489 non-null    str
 2   impacted_workforce_percentage  489 non-null    str
 3   reported_date                  489 non-null    str
 4   industry                       489 non-null    str
 5   headquarter_location           489 non-null    str
 6   sources                        489 non-null    str
 7   status                         489 non-null    str
 8   additional_notes               22 non-null     str
dtypes: str(9)
memory usage: 34.5 KB

In [6]:
df.shape

(489, 9)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 489 entries, 0 to 488
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company                        489 non-null    str
 1   total_layoffs                  489 non-null    str
 2   impacted_workforce_percentage  489 non-null    str
 3   reported_date                  489 non-null    str
 4   industry                       489 non-null    str
 5   headquarter_location           489 non-null    str
 6   sources                        489 non-null    str
 7   status                         489 non-null    str
 8   additional_notes               22 non-null     str
dtypes: str(9)
memory usage: 34.5 KB

In [8]:
df.describe()

,company,total_layoffs,impacted_workforce_percentage,reported_date,industry,headquarter_location,sources,status,additional_notes
count,489,489,489,489,489,489,489,489,22
unique,477,150,50,187,289,134,221,2,22
top,Thirty Madison,Unclear,Unclear,2023-01-11,Fintech,San Francisco,TechCrunch,Private,"Per Axios, 22 of the employees laid off were f..."
freq,2,182,133,12,24,136,52,370,1

In [9]:
df["total_layoffs"] = pd.to_numeric(df["total_layoffs"] , errors = 'coerce')

In [10]:
df["total_layoffs"]

0        20.0
1         NaN
2        13.0
3        20.0
4        24.0
        ...
484    9090.0
485       NaN
486       NaN
487       NaN
488       NaN
Name: total_layoffs, Length: 489, dtype: float64

In [11]:
#df.groupby("company")["total_layoffs"].mean()

In [12]:
df["total_layoffs"].isna().sum()

np.int64(182)

In [13]:
df.head(10)

,company,total_layoffs,impacted_workforce_percentage,reported_date,industry,headquarter_location,sources,status,additional_notes
0,C2FO,20.0,2,2022-12-09,"Fintech, payments","Leawood, KS",Kansas City Business Journal,Private,NaN
1,VideoAmp,NaN,2,2022-09-19,Advertising platforms,Los Angeles,Company memo,Private,NaN
2,Amperity,13.0,3,2022-08-20,"Saas, analytics",Seattle,Geekwire,Private,NaN
3,Addepar,20.0,3,2023-01-18,"fintech, data analytics","Mountain View, CA",Fortune,Private,NaN
4,Thirty Madison,24.0,3,2022-05-13,Health Care,New York,Axios,Private,"Per Axios, 22 of the employees laid off were f..."
5,NextRoll,NaN,3,2022-07-08,Marketing Tech,San Francisco,Business Insider,Private,NaN
6,Armis Security,25.0,4,2022-12-08,Cybersecurity,San Francisco,Calcalistech,Private,NaN
7,Foxtrot,26.0,4,2022-09-23,"food and beverage, e-commerce",Chicago,Chicago Business,Private,NaN
8,Headspace Health,50.0,4,2022-12-14,"telehealth, wellness",Los Angeles,Bloomberg,Private,NaN
9,RealSelf,11.0,5,2022-07-21,Beauty tech,Seattle,GeekWire,Private,NaN

In [14]:
df["impacted_workforce_percentage"] = pd.to_numeric(df["impacted_workforce_percentage"],errors = 'coerce')

In [15]:
df["impacted_workforce_percentage"].describe()

count    356.000000
mean      23.876404
std       24.809390
min        1.000000
25%       10.000000
50%       15.000000
75%       25.000000
max      100.000000
Name: impacted_workforce_percentage, dtype: float64

In [16]:
df["impacted_workforce_percentage"].isna().sum()

np.int64(133)

In [17]:
df2 = df[df["impacted_workforce_percentage"] == 100]

In [18]:
df2

,company,total_layoffs,impacted_workforce_percentage,reported_date,industry,headquarter_location,sources,status,additional_notes
234,Butler Hospitality,1000.0,100.0,2022-07-08,Hospitality,New York,TechCrunch,Private,NaN
235,SummerBio,101.0,100.0,2022-06-20,"Health Care, Diagnostics",Menlo Park,Bay Area Inno,Private,NaN
236,Reali,140.0,100.0,2022-08-24,PropTech,"San Mateo, CA",Calcalistech,Private,NaN
237,Fast,400.0,100.0,2022-04-05,Fintech,San Francisco,The Information,Private,NaN
238,Protocol Media,60.0,100.0,2022-11-15,"News, media",San Francisco,CNN,Private,NaN
239,WanderJaunt,85.0,100.0,2022-07-01,"PropTech, Real Estate",San Francisco,Short Term Rentalz,Private,NaN
240,Wyre,NaN,100.0,2023-01-04,"Cryptocurrency, blockchain",San Francisco,Blockworks,Private,NaN
241,Lantern,NaN,100.0,2023-01-06,"E-commerce, consumer lending","Grand Rapids, MI",Lantern CEO Meredith Mahoney,Private,NaN
242,Lora DiCarlo Inc.,NaN,100.0,2022-12-02,"Wellness, consumer goods","Bend, OR",TechCrunch,Private,NaN
243,Bitfront,NaN,100.0,2022-11-29,Cryptocurrency,"Palo Alto, CA",Reuters,Private,NaN
244,Assure,NaN,100.0,2022-11-23,Fintech,Salt Lake City,Axios,Private,NaN
245,GloriFi,NaN,100.0,2022-11-21,Fintech,Dallas,WSJ,Private,NaN
246,Kite,NaN,100.0,2022-11-16,"AI, coding",San Francisco,Kite,Private,NaN
247,Wavely,NaN,100.0,2022-11-10,"hiring, HR","Palo Alto, CA",Wavely,Private,NaN
248,Fifth Season,NaN,100.0,2022-10-28,Vertical farming,Pittsburgh,Pittsburgh Business Journal,Private,NaN
249,Argo AI,NaN,100.0,2022-10-26,Transportation,Pittsburgh,TechCrunch,Private,NaN
250,CommonBond,NaN,100.0,2022-09-09,"FinTech, loan repayments",New York,"David Klein, CEO of CommonBond",Private,NaN
251,The Wing,NaN,100.0,2022-08-31,Coworking,New York,The Information,Private,NaN
252,Edmodo,NaN,100.0,2022-08-16,Edtech,"San Mateo, CA",EdSurge,Private,NaN
253,Haus,NaN,100.0,2022-08-08,food and beverage,"Healdsburg, CA",TechCrunch,Private,NaN
254,BlockFi,NaN,100.0,2022-11-28,Crypto,Jersey City,Decrypt,Private,NaN
255,Pesto,NaN,100.0,2022-09-23,"IT, future of work",San Francisco,Pesto announcement,Private,NaN
256,Kitty Hawk,NaN,100.0,2022-09-21,aerospace,Mountain View,CNBC,Private,NaN
257,Subspace,NaN,100.0,2022-05-13,Media/entertainment,Los Angeles,LinkedIn,Private,NaN
258,Halcyon Health,NaN,100.0,2022-04-15,Health Care,New York,Axios,Private,NaN
259,Ahead,NaN,100.0,2022-04-14,Health Care,"Santa Clara, CA",Bloomberg,Private,NaN

In [19]:
df.describe()

       total_layoffs  impacted_workforce_percentage
count     307.000000                     356.000000
mean      450.019544                      23.876404
std      1652.123678                      24.809390
min         5.000000                       1.000000
25%        44.000000                      10.000000
50%        95.000000                      15.000000
75%       200.000000                      25.000000
max     18000.000000                     100.000000

In [20]:
df.loc[df["total_layoffs"].isna() , "total_layoffs"] = np.random.randint(df["total_layoffs"].min() , df["total_layoffs"].max(),df["total_layoffs"].isna().sum())

In [21]:
df.loc[df["impacted_workforce_percentage"].isna() , "impacted_workforce_percentage"] = np.random.randint(df["impacted_workforce_percentage"].min() , df["impacted_workforce_percentage"].max(),df["impacted_workforce_percentage"].isna().sum())

In [22]:
df["impacted_workforce_percentage"].isna().sum()

np.int64(0)

In [23]:
df["total_layoffs"].isna().sum()

np.int64(0)

In [24]:
df

,company,total_layoffs,impacted_workforce_percentage,reported_date,industry,headquarter_location,sources,status,additional_notes
0,C2FO,20.0,2.0,2022-12-09,"Fintech, payments","Leawood, KS",Kansas City Business Journal,Private,NaN
1,VideoAmp,1505.0,2.0,2022-09-19,Advertising platforms,Los Angeles,Company memo,Private,NaN
2,Amperity,13.0,3.0,2022-08-20,"Saas, analytics",Seattle,Geekwire,Private,NaN
3,Addepar,20.0,3.0,2023-01-18,"fintech, data analytics","Mountain View, CA",Fortune,Private,NaN
4,Thirty Madison,24.0,3.0,2022-05-13,Health Care,New York,Axios,Private,"Per Axios, 22 of the employees laid off were f..."
...,...,...,...,...,...,...,...,...,...
484,Salesforce,9090.0,47.0,2023-01-04,"enterprise tech, analytics",San Francisco,New York Times,Public,NaN
485,Oracle,6149.0,30.0,2022-08-01,"SaaS, enterprise software",Austin,The Information,Public,The Information reported thousands of people w...
486,LivePerson,3568.0,22.0,2022-09-15,Customer service,New York,LinkedIn,Public,NaN
487,Skillz,3725.0,5.0,2022-08-29,"Mobile Apps, Gaming",San Francisco,Seeking Alpha,Public,NaN
488,Blueboard,5472.0,48.0,2022-11-03,Enterprise Software,San Francisco,LinkedIn reports,Private,NaN

In [25]:
df.isna().sum()

company                            0
total_layoffs                      0
impacted_workforce_percentage      0
reported_date                      0
industry                           0
headquarter_location               0
sources                            0
status                             0
additional_notes                 467
dtype: int64

In [26]:
df.to_csv("tech_layoffs3.csv",index = False)

In [28]:
df["reported_date"] = pd.to_datetime(df["reported_date"])

In [29]:
df["reported_year"] = df["reported_date"].dt.year